language: python

matrix:
  include:
    PYTHON_VERSION:
      - 2.7
      - 3.5
      - 3.6
      - 3.7

before_install:
- git clone https://github.com/ericdill/ci ~/scripts

install:
- . ~/scripts/install-miniconda.sh
- conda create -n testenv-$PYTHON_VERSION python=$PYTHON_VERSION pip
- source activate testenv-$PYTHON_VERSION
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- kernda -h
- coverage run -m pytest -vrsx

after_success:
- codecov
