language: python

python:
- 2.7
- 3.4
- 3.5

install:
- git clone https://github.com/ericdill/ci ~/scripts
- . ~/scripts/install-miniconda.sh
- pip install -r test-requirements.txt
- pip install -e .

script:
- kernda -h

