sudo: false
dist: trusty
matrix:
  include:
    - name: "Python 2.7 unit tests"
      env: PYTHON=2.7
    - name: "Python 3.5 unit tests"
      env: PYTHON=3.5
    - name: "Python 3.6 unit tests"
      env: PYTHON=3.6
    - name: "Python 3.7 unit tests"
      env: PYTHON=3.7

before_install:
- git clone https://github.com/ericdill/ci ~/scripts

install:
- . ~/scripts/install-miniconda.sh
- conda create -n testenv-$PYTHON python=$PYTHON pip
- source activate testenv-$PYTHON
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- kernda -h
- coverage run -m pytest -vrsx

after_success:
- codecov
